# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Ontology tests

on: [push, pull_request, workflow_dispatch]

jobs:
  pytest_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
  robot_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ROBOT
        run: |
          wget --quiet https://github.com/ontodev/robot/releases/download/v1.8.1/robot.jar
          curl https://raw.githubusercontent.com/ontodev/robot/master/bin/robot > robot 
          chmod +x robot
          sudo mv ./robot /usr/local/bin
          sudo mv ./robot.jar /usr/local/bin
          echo "ROBOT version:"
          robot -V
      - name: test for ERRORs with ROBOT report
        run: |
          robot report --input aeon.ttl
      - name: produce report
        run: |
          robot report --input aeon.ttl --output report.txt
      - name: report artifact
        uses: actions/upload-artifact@v2
        with:
          name: robot_report
          path: report.txt